package pedido.form;   import javax.servlet.http.HttpServletRequest; import maestro.control.gstproducto;import maestro.entity.producto;   import org.apache.struts.action.ActionErrors;    import org.apache.struts.action.ActionForm;   import org.apache.struts.action.ActionMapping;   import pedido.control.*;   import pedido.entity.*;import org.apache.struts.action.ActionMessage;  /** * CLASE GENERADA CON generator V3.0 By pablito****** */public class packing_detalleForm  extends ActionForm { 
private String packdcodsx;private String packdpacking;private String packdproducto;/** * @uml.property  name="packdtotal" */private String packdtotal; private String opcion;  /** * @uml.property  name="promodelo" */private String promodelo; /** * @uml.property  name="prodesc" */private String prodesc;  /** * @uml.property  name="packdpesoneto" */private String packdpesoneto;/** * @uml.property  name="packdpesobruto" */private String packdpesobruto; /** * @uml.property  name="packdcantidad" */private String packdcantidad;
 public void setopcion(String newopcion) { this.opcion = newopcion; }
 public String getopcion() { return this.opcion; }
public String getpackdcodsx() {return packdcodsx;}public String getpackdpacking() {return packdpacking;}public String getpackdproducto() {return packdproducto;}public void setpackdcodsx(String new_packdcodsx) {this.packdcodsx =  new_packdcodsx;}public void setpackdpacking(String new_packdpacking) {this.packdpacking =  new_packdpacking;}public void setpackdproducto(String new_packdproducto) {this.packdproducto =  new_packdproducto;} public void reset(ActionMapping mapping, HttpServletRequest request) {  	}  public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) { 
ActionErrors errors = new ActionErrors(); 
 gstpacking_detalle gpacking_detalle= new gstpacking_detalle(); 
 opcion = opcion==null ? "crear" : opcion; 
 if(opcion.equals("set") || opcion.equals("delete")   ) return null; 
 if(opcion.equals("crear")   ) { 
 //@todo COMPLETAR EL CREAR, SOLO LLAVES UNICAS O REPETIDAS 
} 

//valido campos requeridos:   if(packdpacking.equals("")) errors.add("packdpacking", new ActionMessage("El packdpacking no puede ser vacio", false) );     if(packdproducto.equals("")) errors.add("packdproducto", new ActionMessage("El producto no puede ser vacio", false) );     if(packdtotal.equals("")) errors.add("packdtotal", new ActionMessage("la cantidad no puede ser vacio", false) );   try { 	  float total= Float.parseFloat(packdtotal);	   if(total==0) errors.add("packdtotal", new ActionMessage("La cantidad debe ser mayor que CERO", false) );   }catch(NumberFormatException nex) {	   errors.add("packdtotal", new ActionMessage("la cantidad no puede ser letras", false) );   }   
  if(!errors.isEmpty()) errors.add("general", new ActionMessage("No se pudo guardar , revise", false) );  
 return errors; 
 } 

 public void llenar (packing_detalle entity ) { 
 

this.packdcodsx =  entity.getpackdcodsx(); this.packdpacking =  entity.getpackdpacking(); this.packdproducto =  entity.getpackdproducto();this.packdtotal = "";//entity.getPackdtotal();gstproducto gprod = new gstproducto();producto prod = packdproducto==null ? null :  gprod.getproducto( packdproducto);if(prod!=null) {	prodesc = prod.getprodescripcion();	promodelo = prod.getpromodelo();}this.packdpesobruto=  entity.getPackdpesobruto();this.packdpesoneto =  entity.getPackdpesoneto();this.packdcantidad = entity.getPackdcantidad(); }/** * @return * @uml.property  name="prodesc" */public String getProdesc() {	return prodesc;}/** * @param prodesc * @uml.property  name="prodesc" */public void setProdesc(String prodesc) {	this.prodesc = prodesc;}/** * @return * @uml.property  name="promodelo" */public String getPromodelo() {	return promodelo;}/** * @param promodelo * @uml.property  name="promodelo" */public void setPromodelo(String promodelo) {	this.promodelo = promodelo;}/** * @return * @uml.property  name="packdtotal" */public String getPackdtotal() {	return packdtotal;}/** * @param packdtotal * @uml.property  name="packdtotal" */public void setPackdtotal(String packdtotal) {	this.packdtotal = packdtotal;}/** * @return * @uml.property  name="packdpesobruto" */public String getPackdpesobruto() {	return packdpesobruto;}/** * @param packdpesobruto * @uml.property  name="packdpesobruto" */public void setPackdpesobruto(String packdpesobruto) {	this.packdpesobruto = packdpesobruto;}/** * @return * @uml.property  name="packdpesoneto" */public String getPackdpesoneto() {	return packdpesoneto;}/** * @param packdpesoneto * @uml.property  name="packdpesoneto" */public void setPackdpesoneto(String packdpesoneto) {	this.packdpesoneto = packdpesoneto;}/** * @return * @uml.property  name="packdcantidad" */public String getPackdcantidad() {	return packdcantidad;}/** * @param packdcantidad * @uml.property  name="packdcantidad" */public void setPackdcantidad(String packdcantidad) {	this.packdcantidad = packdcantidad;}
}
