select
trafnumdta as "#IMPO"
, ltrafproveedor as "PROVEEDOR"
, promodelo as "MATERIAL"
, prodescripcion as "PRODUCTO"
, prouniempaque as "UMP X ESTIBAS"
, prounimasterpac as "UMP"
, prokiloreal as "PESO X UMP"
, '' as "PUERTO LLEGADA"
, lctrafcontenedor as "CONTENEDOR"
, ctraftamano as "TIPO"
, (select sum(reftcantidad) from referencia_trafico where reftnumfacturatrafico = trafcodsx and reftproducto = procodsx) as "UMP ESPERADAS "
, lctrafcantidad as "UMP RECIBIDAS"
, 0 as "DIF.RECIBO "
, lctrafcantidad as "ESTIBAS RECIBIDAS"
, ltraflote as "LOTE"
, ltrafvencimiento as "F. VENCIMIENTO"
, 0 as "AVERIAS RECIBIDAS"
, 0 as "AVERIAS RECUPERADAS "
, 0 as "AVERIAS TOTALES X UMP"
, 0 as "COSTO X UND DDP"
, 0 as "VALOR AVERIA A DDP"
, '' as "ESTADO DE RECLAMACION"
, 0 as "VALOR PESO AVERIA RECLAMACION"
, '' as "TIPO NOVEDAD"
, '' as "OBSERVACIONES AVERIAS"
, 0 as "VALOR TOTAL RECLAMACION"
, lctrafcantidad/prouniempaque as "ESTIBAS"
, lctrafcantidad*prokiloreal as "PESO NETO"
, lctrafcantidad*prokiloreal as "PESO TOTAL + TARA"
, 0 as "TARA"
, 0 as "TOLERANCIA PESO"
, 0 as "PESO SIN TARA"
, 0 as "DIF. NETO-SIN TARA"
, 0 as "DIFERENCIA"
, 0 as "ITR"
, lctrafcantidad*(select reftpesoneto from referencia_trafico where reftnumfacturatrafico = trafcodsx and reftproducto = procodsx LIMIT 1) as "VALOR FOB"
, transpnombre as "TRANSPORTADOR"
, ctrafplaca as "PLACA"
, ctrafconductor as "NOMBRE DEL CONDUCTOR"
, ctrafcedula as "CEDULA"
, ctrafnumero as "NUMERO DE CONTENEDOR"
, '' as "PRECINTO"
, '' as "NOVEDADES SELLOS"
, '' as "FECHA LEVANTE"
, '' as "SEMANA DE ENTREGA"
, '' as "FECHA ENTREGA PLANILLAS APROX"
, '' as "ETA ESPERADACD"
, '' as "CITA DESCARGUE"
, '' as "ETA REAL CEDI"
, ctrafiniciodescargue as "HORA INGRESO"
, ctraffindescargue as "HORA SALIDA"
, '' as "LUGAR DE DEVOLUCION"
, trafestado as "STATUS"
, '' as "RECIBE LOGISTICA"
, '' as "RESPONSABLE RECLAMACION"
, '' as "ESTADO COSTEO"
, '' as "NOVEDADES COSTEO"
, '' as "AJUSTE INVENTARIO"

from trafico
inner join lote_trafico on ltrafnumtrafico = trafcodsx
inner join producto on procodsx = ltrafcodproducto
inner join lote_contenedor_trafico on lctraflote = ltrafcodsx
inner join contenedor_trafico on ctrafcodsx = lctrafcontenedor
inner join transportadora on transpcodsx = traftransportadora
where promodelo = '12001807'