package administracion.form;   import javax.servlet.http.HttpServletRequest;    import org.apache.struts.action.ActionErrors;    import org.apache.struts.action.ActionForm;   import org.apache.struts.action.ActionMapping;import org.apache.struts.action.ActionMessage; import util.validador;import administracion.control.gstajuste;import administracion.entity.ajuste; /** * CLASE GENERADA CON generator V3.0 By pablito****** */public class ajusteForm  extends ActionForm { 
private String ajcodsx;private String ajcodcia;private String ajingreso;private String ajentrada;private String ajfecha;private String ajsaldoant_nac;private String ajnuevosaldo_nac;private String ajsaldoant_nnac;private String ajnuevosaldo_nnac;/** * @uml.property  name="ajestado" */private String ajestado;/** * @uml.property  name="ajobservacion" */private String ajobservacion; private String opcion; 
 public void setopcion(String newopcion) { this.opcion = newopcion; }
 public String getopcion() { return this.opcion; }
public String getajcodsx() {return ajcodsx;}public String getajcodcia() {return ajcodcia;}public String getajingreso() {return ajingreso;}public String getajentrada() {return ajentrada;}public String getajfecha() {return ajfecha;}public String getajsaldoant_nac() {return ajsaldoant_nac;}public String getajnuevosaldo_nac() {return ajnuevosaldo_nac;}public String getajsaldoant_nnac() {return ajsaldoant_nnac;}public String getajnuevosaldo_nnac() {return ajnuevosaldo_nnac;}public void setajcodsx(String new_ajcodsx) {this.ajcodsx =  new_ajcodsx;}public void setajcodcia(String new_ajcodcia) {this.ajcodcia =  new_ajcodcia;}public void setajingreso(String new_ajingreso) {this.ajingreso =  new_ajingreso;}public void setajentrada(String new_ajentrada) {this.ajentrada =  new_ajentrada;}public void setajfecha(String new_ajfecha) {this.ajfecha =  new_ajfecha;}public void setajsaldoant_nac(String new_ajsaldoant_nac) {this.ajsaldoant_nac =  new_ajsaldoant_nac;}public void setajnuevosaldo_nac(String new_ajnuevosaldo_nac) {this.ajnuevosaldo_nac =  new_ajnuevosaldo_nac;}public void setajsaldoant_nnac(String new_ajsaldoant_nnac) {this.ajsaldoant_nnac =  new_ajsaldoant_nnac;}public void setajnuevosaldo_nnac(String new_ajnuevosaldo_nnac) {this.ajnuevosaldo_nnac =  new_ajnuevosaldo_nnac;} public void reset(ActionMapping mapping, HttpServletRequest request) {  	}  public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) { 
ActionErrors errors = new ActionErrors(); 
 gstajuste gajuste= new gstajuste(); 
 opcion = opcion==null ? "crear" : opcion; 
 if(opcion.equals("set") || opcion.equals("delete")   ) return null; 
 if(opcion.equals("crear")   ) { 
 //@todo COMPLETAR EL CREAR, SOLO LLAVES UNICAS O REPETIDAS 
} 

//valido campos requeridos:   if(ajcodcia.equals("")) errors.add("ajcodcia", new ActionMessage("El ajcodcia no puede ser vacio", false) );     if(ajingreso.equals("")) errors.add("ajingreso", new ActionMessage("El INGRESO no puede ser vacio", false) );     if(ajentrada.equals("")) errors.add("ajentrada", new ActionMessage("Los datos de la entrad no pueden ser vacio", false) );       if(ajsaldoant_nac.equals("")) errors.add("ajsaldoant_nac", new ActionMessage("El ajsaldoant_nac no puede ser vacio", false) );     if(!validador.validarNumero(ajnuevosaldo_nac )) errors.add("ajnuevosaldo_nac", new ActionMessage("El nuevo saldo naC no puede ser vacio y debe ser numerico mayor a cero", false) );     if(ajsaldoant_nnac.equals("")) errors.add("ajsaldoant_nnac", new ActionMessage("El ajsaldoant_nnac no puede ser vacio", false) );     if(!validador.validarNumero(ajnuevosaldo_nnac)) errors.add("ajnuevosaldo_nnac", new ActionMessage("El nuevo saldo NO nac no puede ser vacio y debe ser numerico mayor a cero", false) );  
   if(ajobservacion.equals("")) errors.add("ajobservacion", new ActionMessage("La observacion no puede ser vacio", false) );
  if(!errors.isEmpty()) errors.add("general", new ActionMessage("No se pudo crear , revise", false) );  
 return errors; 
 } 

 public void llenar (ajuste entity ) { 
 

this.ajcodsx =  entity.getajcodsx(); this.ajcodcia =  entity.getajcodcia(); this.ajingreso =  entity.getajingreso(); this.ajentrada =  entity.getajentrada(); this.ajfecha =  entity.getajfecha(); this.ajsaldoant_nac =  entity.getajsaldoant_nac(); this.ajnuevosaldo_nac =  entity.getajnuevosaldo_nac(); this.ajsaldoant_nnac =  entity.getajsaldoant_nnac(); this.ajnuevosaldo_nnac =  entity.getajnuevosaldo_nnac();  this.ajestado = entity.getAjestado();this.ajobservacion =entity.getAjobservacion(); }/** * @return * @uml.property  name="ajestado" */public String getAjestado() {	return ajestado;}/** * @param ajestado * @uml.property  name="ajestado" */public void setAjestado(String ajestado) {	this.ajestado = ajestado;}/** * @return * @uml.property  name="ajobservacion" */public String getAjobservacion() {	return ajobservacion;}/** * @param ajobservacion * @uml.property  name="ajobservacion" */public void setAjobservacion(String ajobservacion) {	this.ajobservacion = ajobservacion;}
}
