package nacionalizacion.form;   import ingreso.control.gstentrada;import ingreso.entity.entrada;import javax.servlet.http.HttpServletRequest;    import org.apache.struts.action.ActionErrors;    import org.apache.struts.action.ActionForm;   import org.apache.struts.action.ActionMapping;   import nacionalizacion.control.*;   import nacionalizacion.entity.*;import org.apache.struts.action.ActionMessage;  /** * CLASE GENERADA CON generator V3.0 By pablito****** */public class nacionalizacion_detalleForm  extends ActionForm { 
private String nadcodsx;private String nadcodnac;/** * @uml.property  name="nadentrada" */private String nadentrada;private String nadcantidad;/** * @uml.property  name="nadsaldo" */private String nadsaldo; private String opcion;  /** * @uml.property  name="nadpesoneto" */private String nadpesoneto;/** * @uml.property  name="nadpesonetototal" */private String nadpesonetototal;/** * @uml.property  name="nadpesobruto" */private String nadpesobruto;/** * @uml.property  name="nadpesobrutototal" */private String nadpesobrutototal;/** * @uml.property  name="nadfob" */private String nadfob;/** * @uml.property  name="nadfobtotal" */private String nadfobtotal; 
 public void setopcion(String newopcion) { this.opcion = newopcion; }
 public String getopcion() { return this.opcion; }
public String getnadcodsx() {return nadcodsx;}public String getnadcodnac() {return nadcodnac;}public String getnadcantidad() {return nadcantidad;}public void setnadcodsx(String new_nadcodsx) {this.nadcodsx =  new_nadcodsx;}public void setnadcodnac(String new_nadcodnac) {this.nadcodnac =  new_nadcodnac;}public void setnadcantidad(String new_nadcantidad) {this.nadcantidad =  new_nadcantidad;} public void reset(ActionMapping mapping, HttpServletRequest request) {  	}  public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) { 
ActionErrors errors = new ActionErrors(); 
 gstnacionalizacion_detalle gnacionalizacion_detalle= new gstnacionalizacion_detalle(); 
 opcion = opcion==null ? "crear" : opcion; 
 if(opcion.equals("set") || opcion.equals("delete")  || opcion.equals("nacionalizar_referencia") || opcion.equals("nacionalizar_referencia_cantidad") ) return null;   
 if(opcion.equals("crear")   ) { 
 //@todo COMPLETAR EL CREAR, SOLO LLAVES UNICAS O REPETIDAS 
} 

//valido campos requeridos:   if(nadcodnac.equals("")) errors.add("nadcodnac", new ActionMessage("El nadcodnac no puede ser vacio", false) );     if(nadentrada.equals("")) errors.add("nadentrada", new ActionMessage("Debe seleccionar un producto del ingreso", false) );     if(nadcantidad.equals("")) errors.add("nadcantidad", new ActionMessage("La Cantidad no puede ser vacio", false) );      //valido que la cantidad no sea mayor al saldo:   if(!nadentrada.equals("")) {   entrada ent = new gstentrada().getentrada(nadentrada);   float saldosinnac = Float.parseFloat( ent.getentsaldosinnac());   float cant = Float.parseFloat(nadcantidad);      if(cant > saldosinnac) errors.add("nadcantidad", new ActionMessage("La cantidad no puede ser mayor al saldo", false) );      }      if(!errors.isEmpty()) errors.add("general", new ActionMessage("No se pudo crear, revise", false) );   return errors; 
 } 

 public void llenar (nacionalizacion_detalle entity ) { 
 

this.nadcodsx =  entity.getnadcodsx(); this.nadcodnac =  entity.getnadcodnac(); this.nadentrada =  entity.getnadentrada(); this.nadcantidad =  entity.getnadcantidad();this.nadpesoneto = entity.getNadpesoneto();this.nadpesobruto = entity.getNadpesobruto();this.nadpesobrutototal = entity.getNadpesobrutototal();this.nadpesonetototal = entity.getNadpesonetototal();this.nadfob = entity.getNadfob();this.nadfobtotal = entity.getNadfobtotal(); }/** * @return * @uml.property  name="nadentrada" */public String getNadentrada() {	return nadentrada;}/** * @param nadentrada * @uml.property  name="nadentrada" */public void setNadentrada(String nadentrada) {	this.nadentrada = nadentrada;}/** * @return * @uml.property  name="nadsaldo" */public String getNadsaldo() {	return nadsaldo;}/** * @param nadsaldo * @uml.property  name="nadsaldo" */public void setNadsaldo(String nadsaldo) {	this.nadsaldo = nadsaldo;}/** * @return * @uml.property  name="nadfob" */public String getNadfob() {	return nadfob;}/** * @param nadfob * @uml.property  name="nadfob" */public void setNadfob(String nadfob) {	this.nadfob = nadfob;}/** * @return * @uml.property  name="nadfobtotal" */public String getNadfobtotal() {	return nadfobtotal;}/** * @param nadfobtotal * @uml.property  name="nadfobtotal" */public void setNadfobtotal(String nadfobtotal) {	this.nadfobtotal = nadfobtotal;}/** * @return * @uml.property  name="nadpesobruto" */public String getNadpesobruto() {	return nadpesobruto;}/** * @param nadpesobruto * @uml.property  name="nadpesobruto" */public void setNadpesobruto(String nadpesobruto) {	this.nadpesobruto = nadpesobruto;}/** * @return * @uml.property  name="nadpesobrutototal" */public String getNadpesobrutototal() {	return nadpesobrutototal;}/** * @param nadpesobrutototal * @uml.property  name="nadpesobrutototal" */public void setNadpesobrutototal(String nadpesobrutototal) {	this.nadpesobrutototal = nadpesobrutototal;}/** * @return * @uml.property  name="nadpesoneto" */public String getNadpesoneto() {	return nadpesoneto;}/** * @param nadpesoneto * @uml.property  name="nadpesoneto" */public void setNadpesoneto(String nadpesoneto) {	this.nadpesoneto = nadpesoneto;}/** * @return * @uml.property  name="nadpesonetototal" */public String getNadpesonetototal() {	return nadpesonetototal;}/** * @param nadpesonetototal * @uml.property  name="nadpesonetototal" */public void setNadpesonetototal(String nadpesonetototal) {	this.nadpesonetototal = nadpesonetototal;}
}
