package pedido.form;   import javax.servlet.http.HttpServletRequest;    import org.apache.struts.action.ActionErrors;    import org.apache.struts.action.ActionForm;   import org.apache.struts.action.ActionMapping;   import pedido.control.*;   import pedido.entity.*;import org.apache.struts.action.ActionMessage;  /** * CLASE GENERADA CON generator V3.0 By pablito****** */public class pickingForm  extends ActionForm { 
private String pickcodsx;private String pickfecha;private String pickempresa;private String pickcodpacking;private String pickobservaciones;private String pickestado; private String opcion;  /** * @uml.property  name="pickdvalorunit" */private String pickdvalorunit; /** * @uml.property  name="pickpedido" */private String pickpedido; /** * @uml.property  name="pickpesoneto" */private String pickpesoneto;/** * @uml.property  name="pickpesobruto" */private String pickpesobruto;/** * @uml.property  name="pickvalor" */private String picknumpedido;private String pickvalor;
 public void setopcion(String newopcion) { this.opcion = newopcion; }
 public String getopcion() { return this.opcion; }
public String getpickcodsx() {return pickcodsx;}public String getpickfecha() {return pickfecha;}public String getpickempresa() {return pickempresa;}public String getpickcodpacking() {return pickcodpacking;}public String getpickobservaciones() {return pickobservaciones;}public String getpickestado() {return pickestado;}public void setpickcodsx(String new_pickcodsx) {this.pickcodsx =  new_pickcodsx;}public void setpickfecha(String new_pickfecha) {this.pickfecha =  new_pickfecha;}public void setpickempresa(String new_pickempresa) {this.pickempresa =  new_pickempresa;}public void setpickcodpacking(String new_pickcodpacking) {this.pickcodpacking =  new_pickcodpacking;}public void setpickobservaciones(String new_pickobservaciones) {this.pickobservaciones =  new_pickobservaciones;}public void setpickestado(String new_pickestado) {this.pickestado =  new_pickestado;} public void reset(ActionMapping mapping, HttpServletRequest request) {  	}  public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) { 
ActionErrors errors = new ActionErrors(); 
 gstpicking gpicking= new gstpicking(); 
 opcion = opcion==null ? "crear" : opcion; 
 if(opcion.equals("set") || opcion.equals("delete")   		 || opcion.equals("activar") || opcion.equals("crear_pedido")) return null; 
 if(opcion.equals("crear")   ) { 
 //@todo COMPLETAR EL CREAR, SOLO LLAVES UNICAS O REPETIDAS 
} 

//valido campos requeridos:   if(pickfecha.equals("")) errors.add("pickfecha", new ActionMessage("El pickfecha no puede ser vacio", false) );     if(pickempresa.equals("")) errors.add("pickempresa", new ActionMessage("La empresa no puede ser vacio", false) );     if(pickcodpacking.equals("")) errors.add("pickcodpacking", new ActionMessage("El Packing asociado no puede ser vacio", false) );  
   pickpedido= pickpedido.equals("") ? null : pickpedido;   
  if(!errors.isEmpty()) errors.add("general", new ActionMessage("No se pudo crear , revise", false) );  
 return errors; 
 } 

 public void llenar (picking entity ) { 
 

this.pickcodsx =  entity.getpickcodsx(); this.pickfecha =  entity.getpickfecha(); this.pickempresa =  entity.getpickempresa(); this.pickcodpacking =  entity.getpickcodpacking(); this.pickobservaciones =  entity.getpickobservaciones(); this.pickestado =  entity.getpickestado();this.pickpesoneto = entity.getPickpesoneto();this.pickpesobruto = entity.getPickpesobruto();this.pickvalor = entity.getPickvalor();this.pickpedido = entity.getPickpedido();this.picknumpedido = entity.getPicknumpedido(); }/** * @return * @uml.property  name="pickdvalorunit" */public String getPickdvalorunit() {	return pickdvalorunit;}/** * @param pickdvalorunit * @uml.property  name="pickdvalorunit" */public void setPickdvalorunit(String pickdvalorunit) {	this.pickdvalorunit = pickdvalorunit;}/** * @return * @uml.property  name="pickpesobruto" */public String getPickpesobruto() {	return pickpesobruto;}/** * @param pickpesobruto * @uml.property  name="pickpesobruto" */public void setPickpesobruto(String pickpesobruto) {	this.pickpesobruto = pickpesobruto;}/** * @return * @uml.property  name="pickpesoneto" */public String getPickpesoneto() {	return pickpesoneto;}/** * @param pickpesoneto * @uml.property  name="pickpesoneto" */public void setPickpesoneto(String pickpesoneto) {	this.pickpesoneto = pickpesoneto;}/** * @return * @uml.property  name="pickvalor" */public String getPickvalor() {	return pickvalor;}/** * @param pickvalor * @uml.property  name="pickvalor" */public void setPickvalor(String pickvalor) {	this.pickvalor = pickvalor;}/** * @return * @uml.property  name="pickpedido" */public String getPickpedido() {	return pickpedido;}/** * @param pickpedido * @uml.property  name="pickpedido" */public void setPickpedido(String pickpedido) {	this.pickpedido = pickpedido;}public String getPicknumpedido() {	return picknumpedido;}public void setPicknumpedido(String picknumpedido) {	this.picknumpedido = picknumpedido;}
}
